#!/usr/bin/env bash
# release-state.sh - Helpers for deployment release-state/evidence snapshots
# shellcheck shell=bash

load_release_state_env() {
  local state_path="$1"

  if [ ! -f "$state_path" ]; then
    log_error "Release state file not found: $state_path"
    return 1
  fi

  set -a
  # shellcheck disable=SC1090
  . "$state_path"
  set +a
}

write_current_release_state() {
  local state_path="$1"

  mkdir -p "$(dirname "$state_path")"

  cat > "$state_path" <<EOF
APP_SHA=${APP_SHA:-}
IMAGE_SOURCE=${IMAGE_SOURCE:-}
CLASSROOMPATH_GATEWAY_IMAGE=${CLASSROOMPATH_GATEWAY_IMAGE:-}
CLASSROOMPATH_MIGRATIONS_IMAGE=${CLASSROOMPATH_MIGRATIONS_IMAGE:-}
OPENPATH_API_IMAGE=${OPENPATH_API_IMAGE:-}
OPENPATH_LINUX_AGENT_VERSION=${OPENPATH_LINUX_AGENT_VERSION:-}
CLASSROOMPATH_SPA_IMAGE=${CLASSROOMPATH_SPA_IMAGE:-}
EOF
}

write_staging_verification_state() {
  local state_path="$1"

  mkdir -p "$(dirname "$state_path")"

  cat > "$state_path" <<EOF
STAGING_VERIFIED_AT=${STAGING_VERIFIED_AT:-}
STAGING_VERIFIED_BY=${STAGING_VERIFIED_BY:-}
STAGING_VERIFIED_APP_SHA=${STAGING_VERIFIED_APP_SHA:-}
STAGING_VERIFIED_OPENPATH_SHA=${STAGING_VERIFIED_OPENPATH_SHA:-}
STAGING_VERIFIED_IMAGE_SOURCE=${STAGING_VERIFIED_IMAGE_SOURCE:-}
STAGING_VERIFIED_GATEWAY_IMAGE=${STAGING_VERIFIED_GATEWAY_IMAGE:-}
STAGING_VERIFIED_MIGRATIONS_IMAGE=${STAGING_VERIFIED_MIGRATIONS_IMAGE:-}
STAGING_VERIFIED_OPENPATH_API_IMAGE=${STAGING_VERIFIED_OPENPATH_API_IMAGE:-}
STAGING_VERIFIED_OPENPATH_LINUX_AGENT_VERSION=${STAGING_VERIFIED_OPENPATH_LINUX_AGENT_VERSION:-}
STAGING_VERIFIED_SPA_IMAGE=${STAGING_VERIFIED_SPA_IMAGE:-}
STAGING_VERIFIED_FIREFOX_RELEASE_ARTIFACTS=${STAGING_VERIFIED_FIREFOX_RELEASE_ARTIFACTS:-}
STAGING_SMOKE_RESULT=${STAGING_SMOKE_RESULT:-}
STAGING_SMOKE_STATUS=${STAGING_SMOKE_STATUS:-}
STAGING_RELEASE_GATE_RESULT=${STAGING_RELEASE_GATE_RESULT:-}
STAGING_WINDOWS_BOOTSTRAP_RESULT=${STAGING_WINDOWS_BOOTSTRAP_RESULT:-}
STAGING_FIREFOX_POLICY_RESULT=${STAGING_FIREFOX_POLICY_RESULT:-}
STAGING_FIREFOX_EXTENSION_ID=${STAGING_FIREFOX_EXTENSION_ID:-}
STAGING_FIREFOX_RELEASE_VERSION=${STAGING_FIREFOX_RELEASE_VERSION:-}
STAGING_FIREFOX_METADATA_SHA256=${STAGING_FIREFOX_METADATA_SHA256:-}
STAGING_FIREFOX_XPI_SHA256=${STAGING_FIREFOX_XPI_SHA256:-}
EOF
}
