#!/usr/bin/env bash

set -euo pipefail

mkdir -p "$STATE_DIR"

if [ ! -f "$STATE_DIR/current-images.env" ]; then
  echo "current-images.env is missing"
  exit 1
fi

set -a
. "$STATE_DIR/current-images.env"
set +a

OPENPATH_SHA="$(git -C "$APP_DIR/upstream/openpath" rev-parse HEAD)"

cat > "$STATE_DIR/staging-verification.env" <<EOF
STAGING_VERIFIED_AT=$STAGING_VERIFIED_AT
STAGING_VERIFIED_BY=deploy-staging-local.sh
STAGING_VERIFIED_APP_SHA=${APP_SHA:-}
STAGING_VERIFIED_OPENPATH_SHA=${OPENPATH_SHA:-}
STAGING_VERIFIED_IMAGE_SOURCE=${IMAGE_SOURCE:-}
STAGING_VERIFIED_GATEWAY_IMAGE=${CLASSROOMPATH_GATEWAY_IMAGE:-}
STAGING_VERIFIED_MIGRATIONS_IMAGE=${CLASSROOMPATH_MIGRATIONS_IMAGE:-}
STAGING_VERIFIED_OPENPATH_API_IMAGE=${OPENPATH_API_IMAGE:-}
STAGING_VERIFIED_OPENPATH_LINUX_AGENT_VERSION=${OPENPATH_LINUX_AGENT_VERSION:-}
STAGING_VERIFIED_SPA_IMAGE=${CLASSROOMPATH_SPA_IMAGE:-}
STAGING_VERIFIED_FIREFOX_RELEASE_ARTIFACTS=$STAGING_FIREFOX_RELEASE_ARTIFACTS
STAGING_SMOKE_RESULT=success
STAGING_SMOKE_STATUS=$STAGING_SMOKE_STATUS
STAGING_RELEASE_GATE_RESULT=success
STAGING_WINDOWS_BOOTSTRAP_RESULT=$STAGING_WINDOWS_BOOTSTRAP_RESULT
STAGING_FIREFOX_POLICY_RESULT=$STAGING_FIREFOX_POLICY_RESULT
STAGING_FIREFOX_EXTENSION_ID=$STAGING_FIREFOX_EXTENSION_ID
STAGING_FIREFOX_RELEASE_VERSION=$STAGING_FIREFOX_RELEASE_VERSION
STAGING_FIREFOX_METADATA_SHA256=$STAGING_FIREFOX_METADATA_SHA256
STAGING_FIREFOX_XPI_SHA256=$STAGING_FIREFOX_XPI_SHA256
EOF
